### PR TITLE
Add listener:dict to on_raw_msg

### PR DESCRIPTION
**Pull request by ArrowAced**
I'm not sure why exactly, but for me this is required for on_raw_msg to work. Might be a good thing to add for compatibility purposes

### CODE REVIEW

**Comment by showierdata9978** [comment]
@ArrowAced its required because of [meower robot](https://github.com/meower-media-co/meower-discord-bot) uses them

**Comment by showierdata9978** [comment]
they came about because of CloudLink turbo

**Comment by melt-exp** [comment]
Thanks for the submission. I agree there may be a compatibility issue here and I'll look into it.

**Comment by melt-exp** [comment]
Uh oh, there's a problem here.

@ArrowAced could you tell me what python version you're using, what meowerbot lib version you're using, and what OS you're using? This might help me resolve the problem quicker.

**Comment by ArrowAced** [comment]
KDE Neon User Edition
Python 3.8 (since that's the maximum KDE Neon supports right now)
Latest meowerbot on pip

**Comment by melt-exp** [comment]
Uhp, looks like the problem was an error on my end. Anyways, this works now that I've resolved my problem, so I'll merge it in a moment.

**Review by melt-exp — APPROVED** [review]

**Pull request merged**
